---
loadbalancer_address: "10.242.36.133"
domain_name: "{{ loadbalancer_address }}.sslip.io"
use_proxy: true

user: data354
apiserver_port: 6443
join_cluster_port: 9345
kube_config_directory: /home/{{ user }}/.kube
rke2_data_dir: /var/lib/rancher/rke2
cluster_token: fbf77b7e4e40d763ad4df32ec9e02d877b112eab

install_rancher: true
install_cert_manager: true
install_longhorn: true
install_keycloack: true
install_airflow_requirements: true
install_monitoring_cluster: false
install_monitoring_stack: false

install_rke2_version: v1.24.10+rke2r1

k8s_services_nodeport:
  - name: svc-1
    port: 30000
  - name: svc-2
    port: 30001
  - name: svc-3
    port: 30002
  - name: svc-4
    port: 30003
  - name: svc-5
    port: 30004