---
loadbalancer_addresses: ["10.240.0.2", "master-ansible"]
loadbalancer_public_address: "104.154.51.12"
public_domain_name: "{{ loadbalancer_public_address }}.sslip.io"

user: k8s
apiserver_port: 6443
join_cluster_port: 9345
kube_config_directory: /home/{{ user }}/.kube
cluster_token: fbf77b7e4e40d763ad4df32ec9e02d877b112eab

install_rancher: false
install_cert_manager: true
install_longhorn: true
install_airflow_requirements: false
install_airflow: false
install_monitoring_cluster: false
install_monitoring_stack: false

install_rke2_version: v1.24.10+rke2r1

k8s_services_nodeport: []
  # - name: airflow-ui
  #   port: 30000