---
- name: Install rke2-agent
  become: true
  block:
    - name: Copy rke2 repo file on the data plane
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.copy:
        src: rke2.repo
        dest: /etc/yum.repos.d/rancher-rke2-1-24-latest.repo
        mode: "700"

    - name: Create Config Folder
      ansible.builtin.file:
        mode: "700"
        path: /etc/rancher/rke2
        state: directory

    - name: Set rke2 config
      ansible.builtin.template:
        mode: "700"
        src: rke2-config.j2
        dest: /etc/rancher/rke2/config.yaml

    - name: Wait for port 9345 to become open on the host
      ansible.builtin.wait_for:
        host: "{{groups['control_plane'][0]}}"
        port: 9345

    - name: Install rke2 agent on the data plane [RedHat]
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.yum:
        state: present
        name: rke2-agent
    
    - name: Start rke2-agent service
      ansible.builtin.service:
        name: rke2-agent
        state: started
        enabled: true