apiVersion: v1
kind: Namespace
metadata:
  name: oci-ihm
  labels:
    name: oci-ihm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oci-ihm
  name: ihm-front
  labels:
    app: ihm-front
spec:
  selector:
    matchLabels:
      app: ihm-front
  template:
    metadata:
      labels:
        app: ihm-front
    spec:
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: ihm-front
          image: us-central1-docker.pkg.dev/gps-oci/gps-oci-front/gps-oci-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: oci-ihm
  name: ihm-front-svc
spec:
  selector:
    app: ihm-front
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: oci-ihm
  name: ihm-ingress
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx
  rules:
    - host: ihm-{{ loadbalancer_address }}.sslip.io
      http:
        paths:
          - backend:
              service:
                name: ihm-front-svc
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ihm-{{ loadbalancer_address }}.sslip.io
      secretName: identity-certificate-secret
