{
 "title": "AIRFLOW LOGS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SPARK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"spark\"} |= `INFO` [$__interval])"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"spark\"} | logfmt"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"spark\"} |= `WARN` [$__interval])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"spark\"} |= `error` | logfmt"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"spark\"} |= `error` [$__interval])"
    }
   ]
  },
  {
   "title": "SCHEDULER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Infos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"scheduler\"} |= `INFO` [$__interval])"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"scheduler\"} |= `` | logfmt"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count_over_time({job=\"scheduler\"} |= `WARN` [$__interval])"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 25 },
   "targets": [
    {
     "expr": "{job=\"scheduler\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"scheduler\"} |= `ERROR` [$__interval])"
    }
   ]
  },
  { "title": "DAG PROCESSING / WORKER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Infos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"worker\"} |= `\\\"levelname\\\": \\\"INFO\\\"` [$__interval])"
    }
   ]
  },
  {
   "title": "Dag run logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 34 },
   "targets": [
    {
     "expr": "{job=\"worker\"} |= `` | logfmt"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"worker\"} |= `\\\"levelname\\\": \\\"ERROR\\\"` [$__interval])"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 41 },
   "targets": [
    {
     "expr": "{job=\"worker\"} |= `\\\"levelname\\\": \\\"ERROR\\\"`"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"worker\"} |= `\\\"levelname\\\": \\\"WARNING\\\"` [$__interval])"
    }
   ]
  }
 ]
}