---
- name: Setting up kube config
  become: true
  block:
    - name: Create kube config Folder
      ansible.builtin.file:
        state: directory
        mode: "707"
        path: "{{ kube_config_directory }}"

    - name: Download kubeconfig file
      delegate_to: "{{groups['control_plane'][0]}}"
      ansible.builtin.fetch:
        flat: true
        src: /etc/rancher/rke2/rke2.yaml
        dest: "{{ kube_config_directory }}/config"
        mode: "707"

    - name: Replace api server ip by loadbalancer ip
      ansible.builtin.replace:
        path: "{{ kube_config_directory }}/config"
        regexp: '127\.0\.0\.1'
        replace: '{{ loadbalancer_addresses[0] }}'

- name: Install Kubectl
  become: true
  block:
    - name: Get kubectl bin from control-pane master
      delegate_to: "{{groups['control_plane'][0]}}"
      ansible.builtin.fetch:
        src: /var/lib/rancher/rke2/bin/kubectl
        dest: ./kubectl
        flat: true
        mode: "707"

    - name: Create kubernetes bin file on master ansible
      ansible.builtin.copy:
        src: ./kubectl
        dest: /usr/bin/kubectl
        mode: "707"