---
- name: Install apps
  hosts: localhost
  tags: apps
  gather_facts: false
  roles:
    - role: apps/cert_manager
      when: install_cert_manager
    - role: apps/rancher
      when: install_rancher
    - role: apps/storage
      when: install_longhorn
    - role: apps/monitoring-cluster
      when: install_monitoring_cluster
    - role: apps/monitoring-stack
      when: install_monitoring_stack
    - role: apps/keycloak
      when: install_keycloak
    - role: apps/ihm
      when: install_ihm
    - role: apps/airflow_requirements
      when: install_airflow_requirements