---
- name: Install helm plugin diff
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install helm plugin diff
      failed_when: false
      ansible.builtin.command:
        cmd: helm plugin install https://github.com/databus23/helm-diff

- name: Install apps
  hosts: localhost
  tags: apps
  gather_facts: false
  roles:
    - apps/cert_manager
    - apps/rancher
    - apps/storage
    - apps/monitoring-cluster
    - apps/monitoring-stack
    - apps/airflow