---
- name: Install apps
  hosts: localhost
  tags: apps
  gather_facts: false
  roles:
    - apps/cert_manager
    - apps/rancher
    - apps/storage
    - apps/monitoring-cluster
    - apps/monitoring-stack
    - apps/airflow