---
- name: Install rke2-server
  become: true
  block:
    - name: Copy rke2 repo file on the control plane
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.copy:
        src: rke2.repo
        dest: /etc/yum.repos.d/rancher-rke2-1-24-latest.repo
        mode: "700"

    - name: Create Config Folder
      ansible.builtin.file:
        mode: "700"
        path: /etc/rancher/rke2
        state: directory

    - name: Set rke2 config
      ansible.builtin.template:
        mode: "700"
        src: rke2-config.j2
        dest: /etc/rancher/rke2/config.yaml
    
    - name: Install rke2 server on the control plane [RedHat]
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.yum:
        state: present
        name: rke2-server

- name: Run primary server service
  become: true
  when: master | bool
  block:
    - name: Start rke2-server service
      become: true
      ansible.builtin.service:
        name: rke2-server
        state: started
        enabled: true

    - name: Wait for port 9345 to become open on the host
      ansible.builtin.wait_for:
        host: "{{groups['control_plane'][0]}}"
        port: 9345

- name: Run secondary server service
  become: true
  when: not master | bool
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: true
